name: Scrape oglase i po≈°alji mail

on:
  schedule:
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 21 * * *'  # 21:00 UTC (22:00 hrvatskog ljeti je 20:00 UTC)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koda
        uses: actions/checkout@v3

      - name: Postavi Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instaliraj ovisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install

      - name: Pokreni scraper
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: |
          python main.py
